<#
.SYNOPSIS
    Safe temp-file cleanup script for Windows endpoints (PowerShell 5.1).

.DESCRIPTION
    Cleans temp files by moving eligible files to a rollback store, not permanent deletion.
    Supports dry-run mode, age-based filtering, per-file error handling, action logging,
    end-of-run summary, rollback, and idempotent execution behavior.
#>

[CmdletBinding()]
param(
    [Parameter()]
    [switch]$DryRun,

    [Parameter()]
    [ValidateRange(0,3650)]
    [int]$OlderThanDays = 0,

    [Parameter()]
    [string[]]$TargetPaths = @($env:TEMP),

    [Parameter()]
    [switch]$IncludeWindowsTemp,

    [Parameter()]
    [string]$LogDirectory = (Join-Path $PSScriptRoot "logs"),

    [Parameter()]
    [string]$RollbackRoot = (Join-Path $PSScriptRoot "rollback-store"),

    [Parameter()]
    [switch]$Rollback,

    [Parameter()]
    [string]$RollbackManifestPath
)

# --------------------------------------------------
# SECTION: Utility Functions
# What this section does:
#   Provides helper functions for logging, lock checks, backup path
#   construction, and summary output.
# --------------------------------------------------
function Write-Log {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Message,

        [Parameter()]
        [ValidateSet('INFO','WARN','ERROR')]
        [string]$Level = 'INFO'
    )

    $line = "[{0}] [{1}] {2}" -f (Get-Date -Format "yyyy-MM-dd HH:mm:ss"), $Level, $Message
    Add-Content -Path $script:LogFile -Value $line -Encoding UTF8
    Write-Host $line
}

function Test-FileLocked {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    try {
        $stream = [System.IO.File]::Open($Path, [System.IO.FileMode]::Open, [System.IO.FileAccess]::ReadWrite, [System.IO.FileShare]::None)
        if ($null -ne $stream) {
            $stream.Close()
            $stream.Dispose()
        }
        return $false
    }
    catch [System.IO.IOException] {
        return $true
    }
    catch {
        return $true
    }
}

function Get-BackupPath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$SourcePath,

        [Parameter(Mandatory = $true)]
        [string]$RunFolder
    )

    $fullPath = [System.IO.Path]::GetFullPath($SourcePath)
    $root = [System.IO.Path]::GetPathRoot($fullPath)
    $drive = $root.TrimEnd('\\').TrimEnd(':')
    $relative = $fullPath.Substring($root.Length)

    return (Join-Path (Join-Path $RunFolder (Join-Path "files" $drive)) $relative)
}

function Write-Summary {
    param(
        [Parameter(Mandatory = $true)]
        [hashtable]$Summary,

        [Parameter(Mandatory = $true)]
        [string]$Title
    )

    Write-Host ""
    Write-Host "===== $Title ====="
    $Summary.GetEnumerator() |
        Sort-Object Name |
        ForEach-Object { Write-Host ("{0}: {1}" -f $_.Key, $_.Value) }
    Write-Host "==========================="
}

# --------------------------------------------------
# SECTION: Initialization
# What this section does:
#   Creates run metadata, initializes directories and log file, and
#   records startup information.
# --------------------------------------------------
$runId = Get-Date -Format "yyyyMMdd-HHmmss"

if (-not (Test-Path -LiteralPath $LogDirectory)) {
    New-Item -ItemType Directory -Path $LogDirectory -Force | Out-Null
}

$script:LogFile = Join-Path $LogDirectory ("temp-cleanup-{0}.log" -f $runId)
New-Item -ItemType File -Path $script:LogFile -Force | Out-Null

Write-Log -Message "Starting script on computer '$env:COMPUTERNAME'."
Write-Log -Message "Mode: $([string]::Format('DryRun={0}; Rollback={1}; OlderThanDays={2}', $DryRun, $Rollback, $OlderThanDays))"

# --------------------------------------------------
# SECTION: Rollback Mode
# What this section does:
#   Restores files from a manifest generated by a previous cleanup run.
#   Uses per-file try/catch and logs each action.
# --------------------------------------------------
if ($Rollback) {
    $rollbackSummary = @{
        TotalEntries       = 0
        Restored           = 0
        WouldRestore       = 0
        MissingBackup      = 0
        SkippedExisting    = 0
        Errors             = 0
    }

    if ([string]::IsNullOrWhiteSpace($RollbackManifestPath)) {
        Write-Log -Level ERROR -Message "Rollback mode requires -RollbackManifestPath."
        Write-Summary -Summary $rollbackSummary -Title "Rollback Summary"
        return
    }

    if (-not (Test-Path -LiteralPath $RollbackManifestPath)) {
        Write-Log -Level ERROR -Message "Rollback manifest not found: $RollbackManifestPath"
        Write-Summary -Summary $rollbackSummary -Title "Rollback Summary"
        return
    }

    try {
        $manifest = Get-Content -LiteralPath $RollbackManifestPath -Raw -ErrorAction Stop | ConvertFrom-Json -ErrorAction Stop
    }
    catch {
        Write-Log -Level ERROR -Message "Failed to read rollback manifest '$RollbackManifestPath'. Error: $($_.Exception.Message)"
        Write-Summary -Summary $rollbackSummary -Title "Rollback Summary"
        return
    }

    foreach ($entry in $manifest.Operations) {
        $rollbackSummary.TotalEntries++

        try {
            if (-not (Test-Path -LiteralPath $entry.BackupPath)) {
                Write-Log -Level WARN -Message "Backup file missing, skipping restore: $($entry.BackupPath)"
                $rollbackSummary.MissingBackup++
                continue
            }

            if (Test-Path -LiteralPath $entry.OriginalPath) {
                Write-Log -Level WARN -Message "Original already exists, skipping restore: $($entry.OriginalPath)"
                $rollbackSummary.SkippedExisting++
                continue
            }

            if ($DryRun) {
                Write-Log -Message ("[DryRun] Would restore '{0}' to '{1}'" -f $entry.BackupPath, $entry.OriginalPath)
                $rollbackSummary.WouldRestore++
                continue
            }

            $originalParent = Split-Path -Path $entry.OriginalPath -Parent
            if (-not (Test-Path -LiteralPath $originalParent)) {
                New-Item -ItemType Directory -Path $originalParent -Force | Out-Null
            }

            Move-Item -LiteralPath $entry.BackupPath -Destination $entry.OriginalPath -Force -ErrorAction Stop
            Write-Log -Message ("Restored '{0}'" -f $entry.OriginalPath)
            $rollbackSummary.Restored++
        }
        catch {
            Write-Log -Level ERROR -Message ("Rollback failed for '{0}'. Error: {1}" -f $entry.OriginalPath, $_.Exception.Message)
            $rollbackSummary.Errors++
        }
    }

    Write-Log -Message "Rollback run complete."
    Write-Summary -Summary $rollbackSummary -Title "Rollback Summary"
    Write-Host "Log file: $script:LogFile"
    return
}

# --------------------------------------------------
# SECTION: Cleanup Target Resolution
# What this section does:
#   Builds the final list of target temp folders and validates which
#   paths currently exist before scanning files.
# --------------------------------------------------
$resolvedTargets = @()
$resolvedTargets += $TargetPaths

if ($IncludeWindowsTemp) {
    $resolvedTargets += (Join-Path $env:WINDIR "Temp")
}

$existingTargets = $resolvedTargets |
    Where-Object { -not [string]::IsNullOrWhiteSpace($_) } |
    Select-Object -Unique |
    Where-Object { Test-Path -LiteralPath $_ }

if ($existingTargets.Count -eq 0) {
    Write-Log -Level WARN -Message "No valid target paths found. Nothing to do."
    Write-Host "Log file: $script:LogFile"
    return
}

foreach ($target in $existingTargets) {
    Write-Log -Message "Target path enabled: $target"
}

# --------------------------------------------------
# SECTION: Cleanup Preparation
# What this section does:
#   Prepares rollback storage and time filter used to decide which
#   files are eligible for cleanup.
# --------------------------------------------------
$cutoffTime = (Get-Date).AddDays(-1 * $OlderThanDays)
$runFolder = Join-Path $RollbackRoot $runId
$filesStoreRoot = Join-Path $runFolder "files"
$manifestPath = Join-Path $runFolder ("rollback-manifest-{0}.json" -f $runId)

if (-not $DryRun) {
    New-Item -ItemType Directory -Path $filesStoreRoot -Force | Out-Null
}

Write-Log -Message "File age cutoff (LastWriteTime <=): $cutoffTime"

$summary = @{
    Scanned          = 0
    Eligible         = 0
    MovedToRollback  = 0
    WouldDelete      = 0
    SkippedLocked    = 0
    SkippedErrors    = 0
    TargetFolders    = $existingTargets.Count
}

$operations = New-Object System.Collections.Generic.List[object]

# --------------------------------------------------
# SECTION: File Enumeration and Processing
# What this section does:
#   Enumerates files under target folders, applies age filtering,
#   skips locked files, and processes each file with per-file try/catch.
# --------------------------------------------------
foreach ($target in $existingTargets) {
    Write-Log -Message "Scanning target: $target"

    try {
        $files = Get-ChildItem -LiteralPath $target -File -Recurse -Force -ErrorAction Stop
    }
    catch {
        Write-Log -Level ERROR -Message ("Unable to scan '{0}'. Error: {1}" -f $target, $_.Exception.Message)
        continue
    }

    foreach ($file in $files) {
        $summary.Scanned++

        if ($file.LastWriteTime -gt $cutoffTime) {
            continue
        }

        $summary.Eligible++

        if (Test-FileLocked -Path $file.FullName) {
            Write-Log -Level WARN -Message ("Locked/in-use file skipped: {0}" -f $file.FullName)
            $summary.SkippedLocked++
            continue
        }

        if ($DryRun) {
            Write-Log -Message ("[DryRun] Would remove '{0}'" -f $file.FullName)
            $summary.WouldDelete++
            continue
        }

        try {
            $backupPath = Get-BackupPath -SourcePath $file.FullName -RunFolder $runFolder
            $backupParent = Split-Path -Path $backupPath -Parent

            if (-not (Test-Path -LiteralPath $backupParent)) {
                New-Item -ItemType Directory -Path $backupParent -Force | Out-Null
            }

            Move-Item -LiteralPath $file.FullName -Destination $backupPath -Force -ErrorAction Stop

            $operations.Add([pscustomobject]@{
                OriginalPath = $file.FullName
                BackupPath   = $backupPath
                MovedAt      = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
            }) | Out-Null

            Write-Log -Message ("Moved to rollback store: '{0}' -> '{1}'" -f $file.FullName, $backupPath)
            $summary.MovedToRollback++
        }
        catch {
            Write-Log -Level ERROR -Message ("Failed processing '{0}'. Error: {1}" -f $file.FullName, $_.Exception.Message)
            $summary.SkippedErrors++
            continue
        }
    }
}

# --------------------------------------------------
# SECTION: Manifest and Completion
# What this section does:
#   Persists rollback metadata for successful moves and prints summary.
#   This keeps cleanup operations reversible and idempotent.
# --------------------------------------------------
if (-not $DryRun) {
    if ($operations.Count -gt 0) {
        $manifest = [pscustomobject]@{
            RunId       = $runId
            CreatedAt   = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
            Computer    = $env:COMPUTERNAME
            OlderThanDays = $OlderThanDays
            Targets     = $existingTargets
            Operations  = $operations
        }

        try {
            $manifestDirectory = Split-Path -Path $manifestPath -Parent
            if (-not (Test-Path -LiteralPath $manifestDirectory)) {
                New-Item -ItemType Directory -Path $manifestDirectory -Force | Out-Null
            }

            $manifest | ConvertTo-Json -Depth 6 | Set-Content -Path $manifestPath -Encoding UTF8
            Write-Log -Message "Rollback manifest created: $manifestPath"
        }
        catch {
            Write-Log -Level ERROR -Message "Failed to write rollback manifest. Error: $($_.Exception.Message)"
        }
    }
    else {
        Write-Log -Message "No files moved. Rollback manifest not created."
    }
}

Write-Log -Message "Cleanup run complete."
Write-Summary -Summary $summary -Title "Cleanup Summary"
Write-Host "Log file: $script:LogFile"
if (-not $DryRun -and $operations.Count -gt 0) {
    Write-Host "Rollback manifest: $manifestPath"
}
